# Site settings
title: /dev
email: sun.ilth.aha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Recording random thoughts, lessons learned etc
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sthaha.github.io" # the base hostname & protocol for your site
github_username:  sthaha

# Build settings
markdown: kramdown
